---
title: "Upload Anticancerfund"
author: "Ariel Balter"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Knitr
```{r, include=F}
knitr::opts_chunk$set(
  warning=F,
  message=F,
  echo=F,
  error=F,
  number_section=T,
  include=F
)
```

# Libraries
```{r, include=F}
# Load Libraries
library(tidyverse)
library(magrittr)
library(ggplot2)
library(ggbeeswarm)
library(ggtext)
library(knitr)
library(printr)
# library(kableExtra)
library(flextable)
library(DT)
library(here)
library(DBI)
library(bigrquery)
library(jsonlite)

```


# Custom table printing
```{r, include=F}
display_table = function(
  df,
  caption=NULL,
  search=list(regex = TRUE, caseInsensitive = TRUE)
)
{
  num_rows = nrow(df)
  df %>%
    datatable(
      extensions = c('ColReorder', 'Scroller'),
      options = list(
        colReorder=T,
        scroller=T,
        scrollY=300,
        sScrollX=T,
        searchHighlight = TRUE,
        search = search,

        pageLength = num_rows
      ),
      caption = htmltools::tags$caption(
        style = '
        caption-side: top;
        text-align: center;
        color:black;
        font-size:150% ;',
        caption),
      # caption = caption,
      rownames = T
    ) %>%
    formatStyle(columns = colnames(.), fontSize = '50%')
}

```


# Set Up BigQuery
```{r}
bq_deauth()
bq_auth(email="ariel.balter@providence.org")

# cancer_graph_project = "psjh-238522"
cancer_graph_project = "eacri-cancer-graph"
raw_dataset = "drug_targets"
graph_ready_dataset = "gdsc_for_graph"
```


# Create dataset
```{r}
# gdsc_dataset = bq_dataset(cancer_graph_project, dataset)
# 
# if (bq_dataset_exists(gdsc_dataset))
# {
#   bq_dataset_delete(gdsc_dataset, delete_contents = T)
# }
# 
# bq_dataset_create(gdsc_dataset)


gdsc_raw_conn = dbConnect(
  bigrquery::bigquery(),
  project = cancer_graph_project,
  dataset = raw_dataset
)

gdsc_graph_conn = dbConnect(
  bigrquery::bigquery(),
  project = cancer_graph_project,
  dataset = graph_ready_dataset
)
```


# Upload with Schema
## Upload Function
```{r}
arrayStringToStringArray = function(data)
{
  data = 
    data %>%
    replace_na(., "") %>% 
    str_split(., ",") %>% 
    lapply(str_trim)
  
  return(data)
}

arrayStringToJSON = function(data)
{
  data = 
    data %>%
    replace_na(., "") %>% 
    str_split(., ",") %>% 
    lapply(str_trim) %>% 
    unlist() %>% 
    toJSON()
  
  return(data)
}

df = data.frame(a = c("a,b , c", "d  , e"))

df %>% mutate(across(a, arrayStringToStringArray))
df %>% mutate(across(a, arrayStringToJSON))
df %>% rowwise() %>% mutate(a = arrayStringToStringArray(a))


arrayStringToStringArray(df$a)

type_map = list(
  INTEGER = "integer",
  FLOAT = "double",
  STRING = "character"
)


bqFieldsToColClasses = function(field_list)
{
  
  # print(fields)
  
  col_classes = lapply(field_list, function(field)
  {
    type_map[[field$type]];
  })
  
  names(col_classes) = lapply(field_list, function(field)
  {
    field$name
  })
  
  # print(col_classezs)
  
  return(col_classes)
}

#gsub("([^,])",'"\\1"', s) %>% sprintf("[%s]",.)

uploadToBQ = function(filename, schema, sep=",")
{
  
  repeated_fields = ""
    
  df = read.csv(
    file=here(filename),
    colClasses = bqFieldsToColClasses(schema),
    stringsAsFactors = F,
    sep=sep
  ) %>% 
  mutate(across(!repeated_fields, arrayStringToStringArray))
  
  table_bq = bq_table(
    project = gdsc_dataset$project, 
    dataset = gdsc_dataset$dataset, 
    table = basename(filename) %>% str_remove(".csv")
  )
  
  if (bq_table_exists(table_bq))
  {
    bq_table_delete(table_bq)
  }
  
  bq_table_upload(
    table_bq,
    quiet = FALSE,
    values = df,
    fields=schema
  )
}

```

# Download Data
https://www.anticancerfund.org/en/cancerdrugs-db

## Raw
```{r}
url = "https://acfdata.coworks.be/cancerdrugsdb.txt"

cancer_drug_target_raw = 
  read.delim(
    url,
    stringsAsFactors = T,
    sep = "\t"
  ) 
```

## Clean
```{r}
cancer_drug_target = 
  cancer_drug_target_raw %>% 
  select(-X) %>% 
  select(
    drug_name = Product,
    drug_bank_link = DrugBank.ID,
    drug_target = Targets,
    indication = Indications,
    year = Year,
    last_updated = Last.Update
  ) %>% 
  # mutate(
  #   drug_bank_id = lapply(drug_bank_link, function(x) str_match(x, "[^>]+>([^<]+)<.*")[2])
  # )
  mutate(
    drug_bank_id = str_match(drug_bank_link, "[^>]+>([^<]+)<.*")[,2],
    drug_target = str_split(drug_target, ",|;"),
    indication = str_split(indication, ",|;"),
    year = as.Date(paste0("01/01/", year), "%d/%m/%y"),
    last_updated = as.Date(last_updated, "%d/%m/%y")
    ) %>% 
  # rowwise() %>%
  # mutate(across(c(drug_target, indication), ~str_split(., ",|;")[1])) %>%
  # rowwise() %>% 
  # mutate(across(c(year, last_update), ~as.Date(., "%m/%d/%y"))) %>% 
  relocate(drug_name, drug_bank_id, drug_target, indication, everything())

c = cancer_drug_target %>% head(3)
  
```


## Upload
```{r}
cancer_drug_target_fields = list(
  bq_field(
    name="drug_name", 
    type="string", 
    description="TBD"
  ),
  bq_field(
    name="drug_bank_id", 
    type="string",
    description = "TBD"
  ),
  bq_field(
    name="drug_target", 
    type="string", 
    mode="repeated", 
    description="TBD"),
  bq_field(
    name="indication",
    type="string",
    mode="repeated",
    description="TBD"
  ),
  bq_field(
    name="EMA", 
    type="string",
    description = "TBD"
  ),
  bq_field(
    name="FDA", 
    type="string",
    description = "TBD"
  ),
  bq_field(
    name="EN", 
    type="string",
    description = "TBD"
  ),
  bq_field(
    name="Other", 
    type="string",
    description = "TBD"
  ),
  bq_field(
    name="WHO", 
    type="string",
    description = "TBD"
  ),
  bq_field(
    name="Year", 
    type="date",
    description = "TBD"
  ),
  bq_field(
    name="Generic", 
    type="String",
    description = "TBD"
  ),
  bq_field(
    name="drug_bank_link", 
    type="string",
    description = "TBD"
  ),
  bq_field(
    name="ATC", 
    type="string",
    description = "TBD"
  ),
  bq_field(
    name="ChEMBL", 
    type="string",
    description = "TBD"
  ),
  bq_field(
    name="last_updated", 
    type="date",
    description = "TBD"
  )
)


cancer_graph_project = "eacri-cancer-graph"
raw_dataset = "drugs_targets"

table_bq = bq_table(cancer_graph_project, raw_dataset, "anticancerfund_drug_target_db")

if (bq_table_exists(table_bq))
{
  bq_table_delete(table_bq)
}

bq_table_upload(
  table_bq,
  quiet = FALSE,
  values = cancer_drug_target,
  fields = cancer_drug_target_fields
)
```

https://rdrr.io/cran/bigQueryR/man/bqr_upload_data.html


